config/routes.rb
Crono::Engine.routes.draw do
  resources :jobs
  root 'jobs#index'
end

app/models/crono/application_record.rb
module Crono
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/crono/crono_job.rb
module Crono
  # Crono::CronoJob is a ActiveRecord model to store job state
  class CronoJob < ActiveRecord::Base
    self.table_name = 'crono_jobs'
    validates :job_id, presence: true, uniqueness: true

    def self.outdated
      self
    end
  end
end

app/controllers/crono/application_controller.rb
module Crono
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/crono/jobs_controller.rb
module Crono
  class JobsController < ApplicationController
    def index
      @jobs = Crono::CronoJob.all
    end

    def show
      @job = Crono::CronoJob.find(params[:id])
    end
  end
end

app/views/crono/jobs/index.html.erb
<header>
  <h4>Running Jobs</h4>
</header>

<div class="responsive-overflow">
  <table id="job_list">
    <tr>
      <th>Job</th>
      <th>Last performed at</th>
      <th>Status</th>
      <th></th>
    </tr>
    <% @jobs.each do |job| %>
      <tr>
        <td>
          <%= job.job_id %>
        </td>
        <td>
          <%= job.last_performed_at || 'Never performed yet' %>
        </td>
        <td>
          <% if job.last_performed_at.nil? %>
            <span class="grey-text darken-3" title="This job has never been performed yet.">
              ◷ Pending
            </span>
          <% elsif job.healthy %>
            <a href="<%= job_path(job) %>">
              <span class="green-text darken-3" title="This job was performed successfully.">
                ✔ Success
              </span>
            </a>
          <% else %>
            <a href="<%= job_path(job) %>">
              <span class="red-text" title="There were problems with this job. Follow the link to check the log.">
                ⚠ Error
              </span>
            </a>
          <% end %>
        </td>
        <td>
          <% if job.last_performed_at %>
            <a href="<%= job_path(job) %>" class="right">
              Log ›
            </a>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/crono/jobs/show.html.erb
<header class="blue-grey lighten-4 grey-text text-darken-4">
  <a href="<%= root_url %>">
    ‹ Back to Home
  </a>
  <h4>Last log of <i><%= @job.job_id %></i>:</h4>
</header>
<% if @job.healthy == false %>
  <div class="row red-text">
    <div class="s12 center-align">
      ⚠
      An error occurs during the last execution of this job.
      Check the log below for details.
    </div>
  </div>
<% end %>
<pre class="responsive-overflow"><%= @job.log %></pre>

app/views/layouts/crono/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"/>
    <title>Crono Dashboard</title>
    <%= stylesheet_link_tag 'crono/materialize.min.css', media: "all" %>
    <%= stylesheet_link_tag 'crono/application', media: "all" %>
    <%= csrf_meta_tags %>
  </head>

  <body class="blue-grey darken-2">
    <nav class="blue-grey white-text" role="navigation">
      <a class="brand-logo center" href="<%= root_path %>">
        <b>Crono</b> Dashboard
      </a>
    </nav>
    <main class="container blue-grey lighten-4">

      <%= yield %>

      <footer class="page-footer blue-grey darken-2">
        <div class="footer-copyright blue-grey">
          Crono v<%= Crono::VERSION %>
          <a class="right" href="https://github.com/plashchynski/crono" target="_blank">Documentation</a>
        </div>
      </footer>
    </main>
  </body>
</html>